# Healthcare Claims Fraud Detection

## Fraud Detection Modeling

This notebook develops and evaluates machine learning models to identify potentially fraudulent healthcare providers. Multiple classification algorithms will be trained and compared using standard evaluation metrics to determine the most effective fraud detection model.

In [26]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)
import plotly.express as px
import plotly.graph_objects as go
import warnings
warnings.filterwarnings("ignore")

## Load Modeling Datasets

In [27]:
X_train = pd.read_csv("../data/modeling/X_train_final.csv")
X_test = pd.read_csv("../data/modeling/X_test_final.csv")
y_train = pd.read_csv("../data/modeling/y_train_final.csv")
y_test = pd.read_csv("../data/modeling/y_test_final.csv")
y_train = y_train.squeeze()
y_test = y_test.squeeze()
print("Datasets Loaded Successfully")

Datasets Loaded Successfully


## Verify Dataset Dimensions

In [28]:
print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (7846, 17)
X_test : (1082, 17)
y_train: (7846,)
y_test : (1082,)


## Logistic Regression Model

In [29]:
log_reg = LogisticRegression(
    random_state=42,
    max_iter=1000
)
log_reg.fit(X_train, y_train)

,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",42
,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",1000
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lb

### Interpretation

The Logistic Regression model was successfully trained using the balanced training dataset.

This model serves as a baseline classifier and will be used as a benchmark for evaluating more advanced algorithms such as Random Forest and XGBoost.

## Generate Predictions

In [30]:
y_pred_lr = log_reg.predict(X_test)
y_prob_lr = log_reg.predict_proba(X_test)[:, 1]
print("Predictions Generated Successfully")

Predictions Generated Successfully


## Evaluate Logistic Regression Performance

In [31]:
lr_accuracy = accuracy_score(y_test, y_pred_lr)
lr_precision = precision_score(y_test, y_pred_lr)
lr_recall = recall_score(y_test, y_pred_lr)
lr_f1 = f1_score(y_test, y_pred_lr)
lr_auc = roc_auc_score(y_test, y_prob_lr)
lr_results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"],
    "Value": [lr_accuracy, lr_precision, lr_recall, lr_f1, lr_auc]
})
lr_results

,Metric,Value
0,Accuracy,0.905730
1,Precision,0.497297
2,Recall,0.910891
3,F1 Score,0.643357
4,ROC-AUC,0.969954


### Interpretation

The Logistic Regression model achieved strong overall performance in detecting fraudulent providers.

Key observations:

- Accuracy: 90.57%
- Recall: 91.09%
- ROC-AUC: 96.99%

The high recall indicates that the model successfully identifies most fraudulent providers, which is important in fraud detection because missing fraudulent cases can be costly.

Although precision is lower (49.73%), this is expected in fraud detection problems where maximizing fraud detection is generally prioritized over minimizing false alarms.

The ROC-AUC score of 0.97 demonstrates excellent class separation capability, indicating that the model effectively distinguishes fraudulent providers from non-fraudulent providers.

## Logistic Regression Confusion Matrix

In [32]:
lr_cm = confusion_matrix(y_test, y_pred_lr)
cm_df = pd.DataFrame(lr_cm,
    index=["Actual Non-Fraud", "Actual Fraud"],
    columns=["Predicted Non-Fraud", "Predicted Fraud"])
cm_df

,Predicted Non-Fraud,Predicted Fraud
Actual Non-Fraud,888,93
Actual Fraud,9,92


### Interpretation

The Logistic Regression model correctly classified the majority of providers.

Results:

- True Negatives (TN): 888
- False Positives (FP): 93
- False Negatives (FN): 9
- True Positives (TP): 92

The model missed only 9 fraudulent providers while successfully identifying 92 fraud cases.

This aligns with the high recall score (91.09%), indicating that the model is highly effective at detecting fraud. Although 93 non-fraud providers were incorrectly flagged as fraud, this tradeoff is generally acceptable in fraud detection applications where identifying fraudulent activity is the primary objective.

## Visualize Confusion Matrix

In [33]:
fig = px.imshow(
    lr_cm,
    text_auto=True,
    color_continuous_scale="Blues",
    labels=dict(
        x="Predicted",
        y="Actual",
        color="Count"
    ),
    x=["Non-Fraud", "Fraud"],
    y=["Non-Fraud", "Fraud"],
    title="Logistic Regression Confusion Matrix"
)
fig.update_layout(
    width=700,
    height=600
)
fig.show()

### Interpretation

The confusion matrix visualization confirms the strong fraud-detection capability of the Logistic Regression model.

Most fraudulent providers were correctly identified, resulting in a very low number of false negatives. This is particularly important in healthcare fraud detection, where failing to detect fraud can lead to substantial financial losses.

While some non-fraud providers were incorrectly flagged as fraudulent, the model prioritizes fraud detection effectiveness over minimizing false alarms.

## Classification Report

In [34]:
print(classification_report(y_test, y_pred_lr, target_names=["Non-Fraud", "Fraud"]))


              precision    recall  f1-score   support

   Non-Fraud       0.99      0.91      0.95       981
       Fraud       0.50      0.91      0.64       101

    accuracy                           0.91      1082
   macro avg       0.74      0.91      0.79      1082
weighted avg       0.94      0.91      0.92      1082



### Interpretation

The Logistic Regression model demonstrates strong fraud detection performance.

For fraudulent providers:

- Precision: 50%
- Recall: 91%
- F1 Score: 64%

The high recall indicates that the model successfully identifies the majority of fraudulent providers, missing only a small number of fraud cases.

For non-fraud providers:

- Precision: 99%
- Recall: 91%
- F1 Score: 95%

The model performs exceptionally well in identifying legitimate providers while maintaining strong fraud detection capability.

Overall, Logistic Regression provides a strong baseline model with excellent ROC-AUC performance and very high fraud recall.

## ROC Curve - Logistic Regression

In [35]:
from sklearn.metrics import roc_curve
fpr_lr, tpr_lr, _ = roc_curve(y_test, y_prob_lr)
fig = go.Figure()
fig.add_trace(
    go.Scatter(
        x=fpr_lr,
        y=tpr_lr,
        mode="lines",
        name=f"Logistic Regression (AUC = {lr_auc:.3f})"
    )
)
fig.add_trace(
    go.Scatter(
        x=[0, 1],
        y=[0, 1],
        mode="lines",
        name="Random Classifier",
        line=dict(dash="dash")
    )
)
fig.update_layout(
    title="ROC Curve - Logistic Regression",
    xaxis_title="False Positive Rate",
    yaxis_title="True Positive Rate",
    width=900,
    height=600
)
fig.show()

### Interpretation

The ROC curve demonstrates excellent classification performance.

The Logistic Regression model achieved an ROC-AUC score of approximately 0.97, indicating a very strong ability to distinguish fraudulent providers from non-fraudulent providers.

The curve remains close to the upper-left corner of the graph, significantly outperforming the random classifier baseline.

An ROC-AUC value above 0.90 is generally considered excellent, suggesting that Logistic Regression is already a highly effective fraud detection model for this dataset.

## Random Forest Classifier

Random Forest is an ensemble learning algorithm that combines multiple decision trees to improve predictive performance.

Advantages include:

- Captures non-linear relationships
- Handles complex feature interactions
- Less sensitive to outliers
- Provides feature importance scores
- Often performs exceptionally well on fraud detection problems

In [36]:
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42,
    n_jobs=-1
)
rf_model.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",200
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",10
,"n_jobs n_jobs: int, default=NoneThe number of jobs to run in parallel. :meth:`fit`, :meth:`predict`,:meth:`decision_path` and :meth:`apply` are all parallelized over thetrees. ``None`` means 1 unless in a :obj:`joblib.parallel_backend`context. ``-1`` means using all processors. See :term:`Glossary<n_jobs>` for more details.",-1
,"random_state random_state: int, RandomState instance or None, default=NoneControls both the randomness of the bootstrapping of the samples usedwhen building trees (if ``bootstrap=True``) and the sampling of thefeatures to consider when looking for the best split at each node(if ``max_features < n_features``).See :term:`Glossary <random_state>` for details.",42
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total n

### Interpretation

The Random Forest model was successfully trained using the balanced training dataset.

Unlike Logistic Regression, Random Forest can capture complex non-linear relationships and feature interactions. This often leads to improved fraud detection performance, particularly when fraudulent behavior patterns are not linearly separable.

## Generate Random Forest Predictions

In [37]:
y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:, 1]
print("Random Forest Predictions Generated Successfully")

Random Forest Predictions Generated Successfully


## Evaluate Random Forest Performance

In [38]:
rf_accuracy = accuracy_score(y_test, y_pred_rf)
rf_precision = precision_score(y_test, y_pred_rf)
rf_recall = recall_score(y_test, y_pred_rf)
rf_f1 = f1_score(y_test, y_pred_rf)
rf_auc = roc_auc_score(y_test, y_prob_rf)
rf_results = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"],
    "Value": [rf_accuracy, rf_precision, rf_recall, rf_f1, rf_auc]})
rf_results

,Metric,Value
0,Accuracy,0.923290
1,Precision,0.560811
2,Recall,0.821782
3,F1 Score,0.666667
4,ROC-AUC,0.961244


### Interpretation

The Random Forest model achieved strong predictive performance and improved overall classification accuracy compared to Logistic Regression.

Key observations:

- Accuracy increased from 90.57% to 92.33%.
- Precision increased from 49.73% to 56.08%.
- F1 Score improved from 64.34% to 66.67%.

However, the recall score decreased from 91.09% to 82.18%, meaning the model missed more fraudulent providers than Logistic Regression.

This highlights the tradeoff between precision and recall. Random Forest generates fewer false alarms but also fails to identify a greater number of fraud cases.

The choice between models will depend on whether maximizing fraud detection (recall) or minimizing false positives (precision) is the primary business objective.

## Random Forest Confusion Matrix

In [39]:
rf_cm = confusion_matrix(y_test, y_pred_rf)
rf_cm_df = pd.DataFrame(rf_cm,
    index=["Actual Non-Fraud", "Actual Fraud"],
    columns=["Predicted Non-Fraud", "Predicted Fraud"]
)
rf_cm_df

,Predicted Non-Fraud,Predicted Fraud
Actual Non-Fraud,916,65
Actual Fraud,18,83


### Interpretation

The Random Forest model correctly classified most providers and reduced the number of false positives compared to Logistic Regression.

Results:

- True Negatives (TN): 916
- False Positives (FP): 65
- False Negatives (FN): 18
- True Positives (TP): 83

Compared to Logistic Regression, Random Forest generated fewer false fraud alerts but missed more fraudulent providers.

This explains the higher precision and lower recall observed in the evaluation metrics. The model is more conservative when labeling providers as fraudulent, reducing false alarms while increasing the risk of missing actual fraud cases.

## Visualize Random Forest Confusion Matrix

In [40]:
fig = px.imshow(
    rf_cm,
    text_auto=True,
    color_continuous_scale="Greens",
    labels=dict(
        x="Predicted",
        y="Actual",
        color="Count"
    ),
    x=["Non-Fraud", "Fraud"],
    y=["Non-Fraud", "Fraud"],
    title="Random Forest Confusion Matrix"
)
fig.update_layout( width=700, height=600)
fig.show()

### Interpretation

The Random Forest confusion matrix shows strong overall classification performance.

The model correctly identified most non-fraudulent providers while maintaining good fraud detection capability. Compared to Logistic Regression, the Random Forest model produces fewer false fraud alerts but misses a larger number of fraudulent providers.

This behavior reflects the higher precision and lower recall observed in the model evaluation metrics.

## Random Forest Feature Importance Analysis

In [41]:
feature_importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": rf_model.feature_importances_
})
feature_importance = feature_importance.sort_values(
    by="Importance",
    ascending=False
)
feature_importance.head(10)

,Feature,Importance
5,MaxLengthOfStay,0.185301
0,InpatientClaimCount,0.111976
3,TotalInpatientReimbursement,0.103701
1,UniqueInpatientBeneficiaries,0.099575
10,TotalOutpatientReimbursement,0.067410
7,OutpatientClaimCount,0.064309
2,AvgInpatientReimbursement,0.057751
16,UniqueBeneficiaries,0.056918
4,AvgLengthOfStay,0.052160
8,UniqueOutpatientBeneficiaries,0.037059


### Interpretation

The Random Forest feature importance analysis identifies the variables that contribute most to fraud prediction.

Top fraud indicators include:

1. MaxLengthOfStay
2. InpatientClaimCount
3. TotalInpatientReimbursement
4. UniqueInpatientBeneficiaries
5. TotalOutpatientReimbursement

These findings closely match the exploratory analysis performed in Notebook 03, where fraudulent providers exhibited significantly higher inpatient activity, longer hospital stays, larger reimbursement amounts, and higher beneficiary volumes.

The results suggest that unusually high healthcare utilization and reimbursement patterns are among the strongest indicators of potential provider fraud.

## Visualize Feature Importance

In [42]:
top_features = feature_importance.head(10)
fig = px.bar(
    top_features.sort_values(by="Importance"),
    x="Importance",
    y="Feature",
    orientation="h",
    title="Top 10 Random Forest Feature Importances",
    text="Importance")
fig.update_traces(
    texttemplate="%{text:.3f}",
    textposition="outside")
fig.update_layout(width=1000, height=600)
fig.show()

### Interpretation

The feature importance visualization highlights the primary drivers of fraud prediction within the Random Forest model.

The most influential variable is MaxLengthOfStay, followed by InpatientClaimCount, TotalInpatientReimbursement, and UniqueInpatientBeneficiaries.

These findings reinforce the exploratory analysis conducted earlier in the project, where fraudulent providers demonstrated substantially higher inpatient activity, longer hospital stays, and larger reimbursement amounts.

The consistency between EDA findings and machine learning feature importance increases confidence in the model's ability to identify meaningful fraud-related patterns.

## Model Performance Comparison

In [43]:
comparison_df = pd.DataFrame({
    "Metric": ["Accuracy", "Precision", "Recall", "F1 Score", "ROC-AUC"],
    "Logistic Regression": [lr_accuracy, lr_precision, lr_recall, lr_f1, lr_auc],
    "Random Forest": [rf_accuracy, rf_precision, rf_recall, rf_f1, rf_auc]
})

comparison_df

,Metric,Logistic Regression,Random Forest
0,Accuracy,0.905730,0.923290
1,Precision,0.497297,0.560811
2,Recall,0.910891,0.821782
3,F1 Score,0.643357,0.666667
4,ROC-AUC,0.969954,0.961244


### Interpretation

Both machine learning models demonstrated strong performance in identifying fraudulent healthcare providers.

Model comparison highlights several tradeoffs:

#### Logistic Regression

Strengths:
- Highest Recall (91.09%)
- Highest ROC-AUC (96.99%)
- Detects more fraudulent providers

Weaknesses:
- Lower Precision (49.73%)
- More false fraud alerts

#### Random Forest

Strengths:
- Highest Accuracy (92.33%)
- Highest Precision (56.08%)
- Highest F1 Score (66.67%)
- Fewer false fraud alerts

Weaknesses:
- Lower Recall (82.18%)
- Misses more fraudulent providers

From a fraud detection perspective, recall is often the most critical metric because failing to identify fraudulent providers can result in significant financial losses.

Therefore, Logistic Regression is selected as the preferred fraud detection model due to its superior fraud detection capability and excellent ROC-AUC performance.

## Select Best Model

In [44]:
best_model = log_reg
print("Selected Model: Logistic Regression")
print(f"ROC-AUC : {lr_auc:.4f}")
print(f"Recall  : {lr_recall:.4f}")

Selected Model: Logistic Regression
ROC-AUC : 0.9700
Recall  : 0.9109


### Interpretation

Based on model evaluation results, Logistic Regression was selected as the final fraud detection model.

Although Random Forest achieved slightly higher accuracy and precision, Logistic Regression produced the highest recall and ROC-AUC score.

Because fraud detection systems prioritize identifying fraudulent activity over minimizing false alerts, Logistic Regression provides the most effective balance for this healthcare fraud detection application.

## Save Final Model

In [45]:
import os
import pickle
os.makedirs("../models", exist_ok=True)
with open("../models/best_fraud_model.pkl", "wb") as file:
    pickle.dump(
        best_model,
        file
    )
print("Model Saved Successfully")

Model Saved Successfully


## Notebook Summary

This notebook developed and evaluated machine learning models for healthcare provider fraud detection.

### Models Developed

#### Logistic Regression
- Trained using the balanced provider dataset.
- Generated fraud probability scores and class predictions.
- Evaluated using multiple classification metrics.

#### Random Forest Classifier
- Trained using ensemble learning techniques.
- Evaluated and compared against Logistic Regression.
- Generated feature importance scores to identify key fraud indicators.

### Model Evaluation Metrics

The following metrics were used:

- Accuracy
- Precision
- Recall
- F1 Score
- ROC-AUC

### Key Findings

#### Logistic Regression
- Accuracy: 90.57%
- Precision: 49.73%
- Recall: 91.09%
- ROC-AUC: 96.99%

#### Random Forest
- Accuracy: 92.33%
- Precision: 56.08%
- Recall: 82.18%
- ROC-AUC: 96.12%

### Feature Importance Insights

The most influential fraud indicators included:

- MaxLengthOfStay
- InpatientClaimCount
- TotalInpatientReimbursement
- UniqueInpatientBeneficiaries
- TotalOutpatientReimbursement

These findings aligned closely with the exploratory analysis results, reinforcing the validity of the identified fraud patterns.

### Final Model Selection

Logistic Regression was selected as the preferred fraud detection model because it achieved:

- Highest Recall
- Highest ROC-AUC
- Strong overall classification performance

The model prioritizes fraud detection effectiveness while maintaining excellent discrimination capability.

### Output Files

- best_fraud_model.pkl

### Outcome

A machine learning solution was successfully developed to identify potentially fraudulent healthcare providers using provider-level healthcare claims data.